application: gpass-5
version: 1
runtime: go
api_version: go1

handlers:
- url: /static
  static_dir: static

- url: /(.*\.(gif|png|jpg|js))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|js)$

- url: /.*
  script: _go_app